name: Build-Publish

on: 
  push:
    branches:
    - master
    paths-ignore:
      - '**.md'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Use yarn
      uses: Borales/actions-yarn@master
    - name: yarn install, lint, build, and test with coverage
      run: |
        yarn install
        yarn lint:all
        yarn build
        yarn cover
      env:
        CI: true

  publish:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - name: Authenticate with registry
        run: echo "//registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN" > $GITHUB_WORKSPACE/.npmrc
        shell: bash
        env:
          NPM_AUTH_TOKEN: ${{secrets.npm_token}}
      - name: Use yarn
        uses: Borales/actions-yarn@master
      - name: Publish
        run: yarn publish:release
        env:
          CI: true